volumes:
  kueue-postgres:
    driver: local

services:

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=kueue
      - POSTGRES_PASSWORD=kueue
      - POSTGRES_DB=kueue
    volumes:
      - kueue-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

